import { mockOpportunities } from "./mock-opportunities"

// Export the opportunities
export { mockOpportunities }

export const mockAccounts = [
  {
    id: "1",
    name: "Acme Corp",
    industry: "Technology",
    dealValue: 500000,
    stage: "Negotiation",
    lastContact: {
      date: "2023-05-13",
      type: "zoom call",
    },
    status: "active",
    customerType: "active",
    totalARR: 250000,
    arrBySolution: {
      orchestrate: 100000,
      digitalOptimization: 75000,
      monetize: 50000,
      opal: 25000,
    },
    openOpportunities: 3,
    buyingCenters: 2,
    contactsEngaged: 12,
    mqls: 5,
    aiSuggestions: 4,
  },
  {
    id: "2",
    name: "Globex Corporation",
    industry: "Manufacturing",
    dealValue: 750000,
    stage: "Proposal",
    lastContact: {
      date: "2023-05-06",
      type: "email",
    },
    status: "prospect",
    customerType: "prospect",
    totalARR: 0,
    arrBySolution: {
      orchestrate: 0,
      digitalOptimization: 0,
      monetize: 0,
      opal: 0,
    },
    openOpportunities: 2,
    buyingCenters: 1,
    contactsEngaged: 8,
    mqls: 3,
    aiSuggestions: 6,
  },
  {
    id: "3",
    name: "Initech",
    industry: "Software",
    dealValue: 300000,
    stage: "Qualified",
    lastContact: {
      date: "2023-05-10",
      type: "phone call",
    },
    status: "inactive",
    customerType: "ex-customer",
    totalARR: 0,
    arrBySolution: {
      orchestrate: 0,
      digitalOptimization: 0,
      monetize: 0,
      opal: 0,
    },
    openOpportunities: 1,
    buyingCenters: 1,
    contactsEngaged: 5,
    mqls: 2,
    aiSuggestions: 2,
  },
  {
    id: "4",
    name: "Wayne Enterprises",
    industry: "Defense",
    dealValue: 1000000,
    stage: "Closing",
    lastContact: {
      date: "2023-05-12",
      type: "zoom call",
    },
    status: "active",
    customerType: "active",
    totalARR: 500000,
    arrBySolution: {
      orchestrate: 200000,
      digitalOptimization: 150000,
      monetize: 100000,
      opal: 50000,
    },
    openOpportunities: 4,
    buyingCenters: 3,
    contactsEngaged: 20,
    mqls: 8,
    aiSuggestions: 7,
  },
  {
    id: "5",
    name: "Stark Industries",
    industry: "Technology",
    dealValue: 600000,
    stage: "Negotiation",
    lastContact: {
      date: "2023-05-08",
      type: "email",
    },
    status: "active",
    customerType: "active",
    totalARR: 350000,
    arrBySolution: {
      orchestrate: 150000,
      digitalOptimization: 100000,
      monetize: 75000,
      opal: 25000,
    },
    openOpportunities: 2,
    buyingCenters: 2,
    contactsEngaged: 15,
    mqls: 6,
    aiSuggestions: 3,
  },
]
