export const mockOpportunities = [
  {
    id: "opp-1",
    name: "Enterprise SaaS Implementation",
    accountId: "1",
    stage: "Proposal",
    value: 250000,
    closeDate: "2023-12-15",
    probability: 70,
    owner: "Jane Smith",
  },
  {
    id: "opp-2",
    name: "Cloud Migration Project",
    accountId: "1",
    stage: "Negotiation",
    value: 180000,
    closeDate: "2023-11-30",
    probability: 85,
    owner: "Jane Smith",
  },
  {
    id: "opp-3",
    name: "Data Analytics Platform",
    accountId: "2",
    stage: "Discovery",
    value: 320000,
    closeDate: "2024-02-28",
    probability: 40,
    owner: "Michael Johnson",
  },
  {
    id: "opp-4",
    name: "Security Infrastructure Upgrade",
    accountId: "3",
    stage: "Proposal",
    value: 150000,
    closeDate: "2024-01-15",
    probability: 60,
    owner: "Robert Davis",
  },
  {
    id: "opp-5",
    name: "Digital Transformation Initiative",
    accountId: "2",
    stage: "Closed Won",
    value: 500000,
    closeDate: "2023-10-15",
    probability: 100,
    owner: "Michael Johnson",
  },
]
