"""Add Template Imprinting Protocol support

Revision ID: 7d10b8475335
Revises: bc652a6512fa
Create Date: 2025-06-22 12:34:19.539328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d10b8475335'
down_revision: Union[str, None] = 'bc652a6512fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imprinting_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template_mode', sa.JSON(), nullable=False),
    sa.Column('template_structure', sa.JSON(), nullable=False),
    sa.Column('example_filled', sa.JSON(), nullable=True),
    sa.Column('forbidden_children', sa.JSON(), nullable=True),
    sa.Column('required_actions', sa.JSON(), nullable=True),
    sa.Column('imprinting_tokens', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('adherence_score', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'agent_type', 'version', name='uq_imprinting_name_agent_version')
    )
    op.create_index('ix_imprinting_active', 'imprinting_templates', ['is_active'], unique=False)
    op.create_index('ix_imprinting_adherence', 'imprinting_templates', ['adherence_score'], unique=False)
    op.create_index('ix_imprinting_agent_type', 'imprinting_templates', ['agent_type'], unique=False)
    op.create_index('ix_imprinting_priority', 'imprinting_templates', ['priority'], unique=False)
    op.create_index('ix_imprinting_tokens', 'imprinting_templates', ['token_count'], unique=False)
    op.add_column('processing_sessions', sa.Column('imprinting_template_id', sa.String(length=36), nullable=True))
    op.add_column('processing_sessions', sa.Column('imprinting_adherence_score', sa.Float(), nullable=True))
    op.add_column('processing_sessions', sa.Column('pattern_violations', sa.Integer(), nullable=True))
    op.add_column('processing_sessions', sa.Column('first_token_effective', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'processing_sessions', 'imprinting_templates', ['imprinting_template_id'], ['id'])
    op.add_column('prompt_templates', sa.Column('template_mode', sa.JSON(), nullable=True))
    op.add_column('prompt_templates', sa.Column('imprinting_tokens', sa.Text(), nullable=True))
    op.add_column('prompt_templates', sa.Column('pattern_adherence_score', sa.Float(), nullable=True))
    op.add_column('prompt_templates', sa.Column('is_imprinting_enabled', sa.Boolean(), nullable=False))
    op.add_column('prompt_templates', sa.Column('template_structure', sa.JSON(), nullable=True))
    op.add_column('prompt_templates', sa.Column('behavioral_constraints', sa.JSON(), nullable=True))
    op.add_column('prompt_templates', sa.Column('imprinting_success_rate', sa.Float(), nullable=True))
    op.create_index('ix_template_adherence', 'prompt_templates', ['pattern_adherence_score'], unique=False)
    op.create_index('ix_template_imprinting', 'prompt_templates', ['is_imprinting_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_template_imprinting', table_name='prompt_templates')
    op.drop_index('ix_template_adherence', table_name='prompt_templates')
    op.drop_column('prompt_templates', 'imprinting_success_rate')
    op.drop_column('prompt_templates', 'behavioral_constraints')
    op.drop_column('prompt_templates', 'template_structure')
    op.drop_column('prompt_templates', 'is_imprinting_enabled')
    op.drop_column('prompt_templates', 'pattern_adherence_score')
    op.drop_column('prompt_templates', 'imprinting_tokens')
    op.drop_column('prompt_templates', 'template_mode')
    op.drop_constraint(None, 'processing_sessions', type_='foreignkey')
    op.drop_column('processing_sessions', 'first_token_effective')
    op.drop_column('processing_sessions', 'pattern_violations')
    op.drop_column('processing_sessions', 'imprinting_adherence_score')
    op.drop_column('processing_sessions', 'imprinting_template_id')
    op.drop_index('ix_imprinting_tokens', table_name='imprinting_templates')
    op.drop_index('ix_imprinting_priority', table_name='imprinting_templates')
    op.drop_index('ix_imprinting_agent_type', table_name='imprinting_templates')
    op.drop_index('ix_imprinting_adherence', table_name='imprinting_templates')
    op.drop_index('ix_imprinting_active', table_name='imprinting_templates')
    op.drop_table('imprinting_templates')
    # ### end Alembic commands ###
