"""Initial database schema

Revision ID: bc652a6512fa
Revises: 
Create Date: 2025-06-22 10:22:18.591679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc652a6512fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configurations',
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type', 'name', 'environment', name='uq_agent_config')
    )
    op.create_index('ix_config_agent_type', 'agent_configurations', ['agent_type'], unique=False)
    op.create_index('ix_config_default', 'agent_configurations', ['is_default'], unique=False)
    op.create_index('ix_config_environment', 'agent_configurations', ['environment'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template_metadata', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'agent_type', name='uq_template_name_agent')
    )
    op.create_index('ix_template_active', 'prompt_templates', ['is_active'], unique=False)
    op.create_index('ix_template_agent_type', 'prompt_templates', ['agent_type'], unique=False)
    op.create_index('ix_template_usage', 'prompt_templates', ['usage_count'], unique=False)
    op.create_table('processing_sessions',
    sa.Column('session_type', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('prompt_template_id', sa.String(length=36), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_agent_type', 'processing_sessions', ['agent_type'], unique=False)
    op.create_index('ix_session_created_at', 'processing_sessions', ['created_at'], unique=False)
    op.create_index('ix_session_source', 'processing_sessions', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_session_status', 'processing_sessions', ['status'], unique=False)
    op.create_index('ix_session_type', 'processing_sessions', ['session_type'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_version_template_version')
    )
    op.create_index('ix_version_current', 'prompt_versions', ['is_current'], unique=False)
    op.create_index('ix_version_template_id', 'prompt_versions', ['template_id'], unique=False)
    op.create_index('ix_version_usage', 'prompt_versions', ['usage_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_version_usage', table_name='prompt_versions')
    op.drop_index('ix_version_template_id', table_name='prompt_versions')
    op.drop_index('ix_version_current', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('ix_session_type', table_name='processing_sessions')
    op.drop_index('ix_session_status', table_name='processing_sessions')
    op.drop_index('ix_session_source', table_name='processing_sessions')
    op.drop_index('ix_session_created_at', table_name='processing_sessions')
    op.drop_index('ix_session_agent_type', table_name='processing_sessions')
    op.drop_table('processing_sessions')
    op.drop_index('ix_template_usage', table_name='prompt_templates')
    op.drop_index('ix_template_agent_type', table_name='prompt_templates')
    op.drop_index('ix_template_active', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index('ix_config_environment', table_name='agent_configurations')
    op.drop_index('ix_config_default', table_name='agent_configurations')
    op.drop_index('ix_config_agent_type', table_name='agent_configurations')
    op.drop_table('agent_configurations')
    # ### end Alembic commands ###
