"""add_evidence_system_tables

Revision ID: d08b255a1e88
Revises: 7d10b8475335
Create Date: 2025-06-23 19:30:25.567774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08b255a1e88'
down_revision: Union[str, None] = '7d10b8475335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('deal_id', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_account', 'documents', ['account_id'], unique=False)
    op.create_index('ix_document_deal', 'documents', ['deal_id'], unique=False)
    op.create_index('ix_document_processed', 'documents', ['is_processed'], unique=False)
    op.create_index('ix_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('ix_document_uploaded', 'documents', ['uploaded_at'], unique=False)
    op.create_table('transcripts',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('deal_id', sa.String(length=100), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_account', 'transcripts', ['account_id'], unique=False)
    op.create_index('ix_transcript_date', 'transcripts', ['meeting_date'], unique=False)
    op.create_index('ix_transcript_deal', 'transcripts', ['deal_id'], unique=False)
    op.create_index('ix_transcript_processed', 'transcripts', ['is_processed'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_index('ix_user_active', 'users', ['is_active'], unique=False)
    op.create_table('document_sections',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_section_document', 'document_sections', ['document_id'], unique=False)
    op.create_index('ix_section_pages', 'document_sections', ['page_start', 'page_end'], unique=False)
    op.create_index('ix_section_type', 'document_sections', ['section_type'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segment_position', 'transcript_segments', ['start_position', 'end_position'], unique=False)
    op.create_index('ix_segment_speaker', 'transcript_segments', ['speaker'], unique=False)
    op.create_index('ix_segment_time', 'transcript_segments', ['start_time'], unique=False)
    op.create_index('ix_segment_transcript', 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('intelligence_evidence',
    sa.Column('analysis_id', sa.String(length=100), nullable=True),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('element_key', sa.String(length=100), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.String(length=10), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_analysis_element', 'intelligence_evidence', ['analysis_id', 'element_type', 'element_key'], unique=False)
    op.create_index('ix_evidence_confidence', 'intelligence_evidence', ['confidence'], unique=False)
    op.create_index('ix_evidence_document', 'intelligence_evidence', ['document_id'], unique=False)
    op.create_index('ix_evidence_transcript', 'intelligence_evidence', ['transcript_id', 'start_position'], unique=False)
    op.create_index('ix_evidence_type', 'intelligence_evidence', ['extraction_type'], unique=False)
    # Foreign key constraint removed for SQLite compatibility
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_sessions', type_='foreignkey')
    op.drop_index('ix_evidence_type', table_name='intelligence_evidence')
    op.drop_index('ix_evidence_transcript', table_name='intelligence_evidence')
    op.drop_index('ix_evidence_document', table_name='intelligence_evidence')
    op.drop_index('ix_evidence_confidence', table_name='intelligence_evidence')
    op.drop_index('ix_evidence_analysis_element', table_name='intelligence_evidence')
    op.drop_table('intelligence_evidence')
    op.drop_index('ix_segment_transcript', table_name='transcript_segments')
    op.drop_index('ix_segment_time', table_name='transcript_segments')
    op.drop_index('ix_segment_speaker', table_name='transcript_segments')
    op.drop_index('ix_segment_position', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index('ix_section_type', table_name='document_sections')
    op.drop_index('ix_section_pages', table_name='document_sections')
    op.drop_index('ix_section_document', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index('ix_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_transcript_processed', table_name='transcripts')
    op.drop_index('ix_transcript_deal', table_name='transcripts')
    op.drop_index('ix_transcript_date', table_name='transcripts')
    op.drop_index('ix_transcript_account', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_document_uploaded', table_name='documents')
    op.drop_index('ix_document_type', table_name='documents')
    op.drop_index('ix_document_processed', table_name='documents')
    op.drop_index('ix_document_deal', table_name='documents')
    op.drop_index('ix_document_account', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
